frr defaults traditional
hostname router1
log stdout
service integrated-vtysh-config
!
! Konfigurasi interface link ke router2 (eth2) dan router4 (eth3)
interface eth2
 ipv6 ospf6 network point-to-point
!
interface eth3
 ipv6 ospf6 network point-to-point
!
router ospf6
 ospf6 router-id 1.1.1.1
 interface eth2 area 0.0.0.0
 interface eth3 area 0.0.0.0
!
