global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'prometheus' # Job untuk memantau Prometheus itu sendiri
    static_configs:
      - targets: ['localhost:9090'] # Ini mengacu pada Prometheus pod itu sendiri

  - job_name: 'containerlab-nodes' # Job untuk node_exporter dari semua node Anda
    static_configs:
      - targets:
          # Menggunakan CLUSTER-IP dari service yang sesuai
          - '10.152.183.200:9100'  # router1 service
          - '10.152.183.55:9100'   # router2 service
          - '10.152.183.109:9100'  # router3 service
          - '10.152.183.207:9100'  # router4 service
          - '10.152.183.229:9100'  # pc1 service
          - '10.152.183.43:9100'   # pc2 service