apiVersion: clabernetes.containerlab.dev/v1alpha1
kind: Topology
metadata:
  name: srv6-mesh
  namespace: c9s-srv6-mesh
spec:
  # Opsi ini untuk mengatasi rate limit Docker Hub (tetap diperlukan)
  imagePull:
    secrets:
      - my-docker-hub-secret
  
  topology:
    nodes:
      # --- SPINE ROUTERS ---
      router1:
        kind: linux
        image: sflow/clab-frr
        # Mounts ConfigMaps to a temporary, writable path
        binds:
          - { mountPath: /tmp/frr.conf, subPath: frr.conf, configMapKeyRef: { name: router1-frr-config, key: frr.conf } }
          - { mountPath: /tmp/daemons, subPath: daemons, configMapKeyRef: { name: router1-daemons-config, key: daemons } }
        # Custom command to copy configs before starting
        command: ["/bin/sh", "-c", "cp /tmp/frr.conf /etc/frr/frr.conf && cp /tmp/daemons /etc/frr/daemons && /start.sh"]
      router2:
        kind: linux
        image: sflow/clab-frr
        binds:
          - { mountPath: /tmp/frr.conf, subPath: frr.conf, configMapKeyRef: { name: router2-frr-config, key: frr.conf } }
          - { mountPath: /tmp/daemons, subPath: daemons, configMapKeyRef: { name: router2-daemons-config, key: daemons } }
        command: ["/bin/sh", "-c", "cp /tmp/frr.conf /etc/frr/frr.conf && cp /tmp/daemons /etc/frr/daemons && /start.sh"]
      router3:
        kind: linux
        image: sflow/clab-frr
        binds:
          - { mountPath: /tmp/frr.conf, subPath: frr.conf, configMapKeyRef: { name: router3-frr-config, key: frr.conf } }
          - { mountPath: /tmp/daemons, subPath: daemons, configMapKeyRef: { name: router3-daemons-config, key: daemons } }
        command: ["/bin/sh", "-c", "cp /tmp/frr.conf /etc/frr/frr.conf && cp /tmp/daemons /etc/frr/daemons && /start.sh"]
      router4:
        kind: linux
        image: sflow/clab-frr
        binds:
          - { mountPath: /tmp/frr.conf, subPath: frr.conf, configMapKeyRef: { name: router4-frr-config, key: frr.conf } }
          - { mountPath: /tmp/daemons, subPath: daemons, configMapKeyRef: { name: router4-daemons-config, key: daemons } }
        command: ["/bin/sh", "-c", "cp /tmp/frr.conf /etc/frr/frr.conf && cp /tmp/daemons /etc/frr/daemons && /start.sh"]

      # --- LEAF ROUTERS ---
      router5:
        kind: linux
        image: sflow/clab-frr
        binds:
          - { mountPath: /tmp/frr.conf, subPath: frr.conf, configMapKeyRef: { name: router5-frr-config, key: frr.conf } }
          - { mountPath: /tmp/daemons, subPath: daemons, configMapKeyRef: { name: router5-daemons-config, key: daemons } }
        command: ["/bin/sh", "-c", "cp /tmp/frr.conf /etc/frr/frr.conf && cp /tmp/daemons /etc/frr/daemons && /start.sh"]
      router6:
        kind: linux
        image: sflow/clab-frr
        binds:
          - { mountPath: /tmp/frr.conf, subPath: frr.conf, configMapKeyRef: { name: router6-frr-config, key: frr.conf } }
          - { mountPath: /tmp/daemons, subPath: daemons, configMapKeyRef: { name: router6-daemons-config, key: daemons } }
        command: ["/bin/sh", "-c", "cp /tmp/frr.conf /etc/frr/frr.conf && cp /tmp/daemons /etc/frr/daemons && /start.sh"]
      # ... Anda perlu melanjutkan pola ini untuk router7 hingga router20 ...
      router7:
        kind: linux
        image: sflow/clab-frr
        binds:
          - { mountPath: /tmp/frr.conf, subPath: frr.conf, configMapKeyRef: { name: router7-frr-config, key: frr.conf } }
          - { mountPath: /tmp/daemons, subPath: daemons, configMapKeyRef: { name: router7-daemons-config, key: daemons } }
        command: ["/bin/sh", "-c", "cp /tmp/frr.conf /etc/frr/frr.conf && cp /tmp/daemons /etc/frr/daemons && /start.sh"]
      router8:
        kind: linux
        image: sflow/clab-frr
        binds:
          - { mountPath: /tmp/frr.conf, subPath: frr.conf, configMapKeyRef: { name: router8-frr-config, key: frr.conf } }
          - { mountPath: /tmp/daemons, subPath: daemons, configMapKeyRef: { name: router8-daemons-config, key: daemons } }
        command: ["/bin/sh", "-c", "cp /tmp/frr.conf /etc/frr/frr.conf && cp /tmp/daemons /etc/frr/daemons && /start.sh"]
      router9:
        kind: linux
        image: sflow/clab-frr
        binds:
          - { mountPath: /tmp/frr.conf, subPath: frr.conf, configMapKeyRef: { name: router9-frr-config, key: frr.conf } }
          - { mountPath: /tmp/daemons, subPath: daemons, configMapKeyRef: { name: router9-daemons-config, key: daemons } }
        command: ["/bin/sh", "-c", "cp /tmp/frr.conf /etc/frr/frr.conf && cp /tmp/daemons /etc/frr/daemons && /start.sh"]
      router10:
        kind: linux
        image: sflow/clab-frr
        binds:
          - { mountPath: /tmp/frr.conf, subPath: frr.conf, configMapKeyRef: { name: router10-frr-config, key: frr.conf } }
          - { mountPath: /tmp/daemons, subPath: daemons, configMapKeyRef: { name: router10-daemons-config, key: daemons } }
        command: ["/bin/sh", "-c", "cp /tmp/frr.conf /etc/frr/frr.conf && cp /tmp/daemons /etc/frr/daemons && /start.sh"]
      router11:
        kind: linux
        image: sflow/clab-frr
        binds:
          - { mountPath: /tmp/frr.conf, subPath: frr.conf, configMapKeyRef: { name: router11-frr-config, key: frr.conf } }
          - { mountPath: /tmp/daemons, subPath: daemons, configMapKeyRef: { name: router11-daemons-config, key: daemons } }
        command: ["/bin/sh", "-c", "cp /tmp/frr.conf /etc/frr/frr.conf && cp /tmp/daemons /etc/frr/daemons && /start.sh"]
      router12:
        kind: linux
        image: sflow/clab-frr
        binds:
          - { mountPath: /tmp/frr.conf, subPath: frr.conf, configMapKeyRef: { name: router12-frr-config, key: frr.conf } }
          - { mountPath: /tmp/daemons, subPath: daemons, configMapKeyRef: { name: router12-daemons-config, key: daemons } }
        command: ["/bin/sh", "-c", "cp /tmp/frr.conf /etc/frr/frr.conf && cp /tmp/daemons /etc/frr/daemons && /start.sh"]
      router13:
        kind: linux
        image: sflow/clab-frr
        binds:
          - { mountPath: /tmp/frr.conf, subPath: frr.conf, configMapKeyRef: { name: router13-frr-config, key: frr.conf } }
          - { mountPath: /tmp/daemons, subPath: daemons, configMapKeyRef: { name: router13-daemons-config, key: daemons } }
        command: ["/bin/sh", "-c", "cp /tmp/frr.conf /etc/frr/frr.conf && cp /tmp/daemons /etc/frr/daemons && /start.sh"]
      router14:
        kind: linux
        image: sflow/clab-frr
        binds:
          - { mountPath: /tmp/frr.conf, subPath: frr.conf, configMapKeyRef: { name: router14-frr-config, key: frr.conf } }
          - { mountPath: /tmp/daemons, subPath: daemons, configMapKeyRef: { name: router14-daemons-config, key: daemons } }
        command: ["/bin/sh", "-c", "cp /tmp/frr.conf /etc/frr/frr.conf && cp /tmp/daemons /etc/frr/daemons && /start.sh"]
      router15:
        kind: linux
        image: sflow/clab-frr
        binds:
          - { mountPath: /tmp/frr.conf, subPath: frr.conf, configMapKeyRef: { name: router15-frr-config, key: frr.conf } }
          - { mountPath: /tmp/daemons, subPath: daemons, configMapKeyRef: { name: router15-daemons-config, key: daemons } }
        command: ["/bin/sh", "-c", "cp /tmp/frr.conf /etc/frr/frr.conf && cp /tmp/daemons /etc/frr/daemons && /start.sh"]
      router16:
        kind: linux
        image: sflow/clab-frr
        binds:
          - { mountPath: /tmp/frr.conf, subPath: frr.conf, configMapKeyRef: { name: router16-frr-config, key: frr.conf } }
          - { mountPath: /tmp/daemons, subPath: daemons, configMapKeyRef: { name: router16-daemons-config, key: daemons } }
        command: ["/bin/sh", "-c", "cp /tmp/frr.conf /etc/frr/frr.conf && cp /tmp/daemons /etc/frr/daemons && /start.sh"]
      router17:
        kind: linux
        image: sflow/clab-frr
        binds:
          - { mountPath: /tmp/frr.conf, subPath: frr.conf, configMapKeyRef: { name: router17-frr-config, key: frr.conf } }
          - { mountPath: /tmp/daemons, subPath: daemons, configMapKeyRef: { name: router17-daemons-config, key: daemons } }
        command: ["/bin/sh", "-c", "cp /tmp/frr.conf /etc/frr/frr.conf && cp /tmp/daemons /etc/frr/daemons && /start.sh"]
      router18:
        kind: linux
        image: sflow/clab-frr
        binds:
          - { mountPath: /tmp/frr.conf, subPath: frr.conf, configMapKeyRef: { name: router18-frr-config, key: frr.conf } }
          - { mountPath: /tmp/daemons, subPath: daemons, configMapKeyRef: { name: router18-daemons-config, key: daemons } }
        command: ["/bin/sh", "-c", "cp /tmp/frr.conf /etc/frr/frr.conf && cp /tmp/daemons /etc/frr/daemons && /start.sh"]
      router19:
        kind: linux
        image: sflow/clab-frr
        binds:
          - { mountPath: /tmp/frr.conf, subPath: frr.conf, configMapKeyRef: { name: router19-frr-config, key: frr.conf } }
          - { mountPath: /tmp/daemons, subPath: daemons, configMapKeyRef: { name: router19-daemons-config, key: daemons } }
        command: ["/bin/sh", "-c", "cp /tmp/frr.conf /etc/frr/frr.conf && cp /tmp/daemons /etc/frr/daemons && /start.sh"]
      router20:
        kind: linux
        image: sflow/clab-frr
        binds:
          - { mountPath: /tmp/frr.conf, subPath: frr.conf, configMapKeyRef: { name: router20-frr-config, key: frr.conf } }
          - { mountPath: /tmp/daemons, subPath: daemons, configMapKeyRef: { name: router20-daemons-config, key: daemons } }
        command: ["/bin/sh", "-c", "cp /tmp/frr.conf /etc/frr/frr.conf && cp /tmp/daemons /etc/frr/daemons && /start.sh"]

      # --- CLIENT PCs (tidak perlu diubah) ---
      pc1:
        kind: linux
        image: sflow/clab-iperf3
        exec:
          - ip addr add 10.0.0.1/24 dev eth1
          - ip route replace default via 10.0.0.2 dev eth1
          - ip -6 addr add 2001:fa::2/64 dev eth1
          - ip -6 route replace default via 2001:fa::1 dev eth1
      pc2:
        kind: linux
        image: sflow/clab-iperf3
        exec:
          - ip addr add 10.0.2.1/24 dev eth1
          - ip route replace default via 10.0.2.2 dev eth1
          - ip -6 addr add 2001:4b::2/64 dev eth1
          - ip -6 route replace default via 2001:4b::1 dev eth1

      # --- MONITORING STACK (tidak perlu diubah) ---
      sflow-rt: { kind: linux, image: sflow/prometheus, ports: [ "8008:8008", "6343:6343/udp" ] }
      prometheus: { kind: linux, image: prom/prometheus:v2.47.0, ports: [ "9090:9090" ], binds: [ "./prometheus_ne.yml:/etc/prometheus/prometheus.yml" ] }
      grafana: { kind: linux, image: grafana/grafana-oss, ports: [ "3000:3000" ], env: { GF_SECURITY_ADMIN_USER: "admin", GF_SECURITY_ADMIN_PASSWORD: "admin" } }
      
    links:
      # --- KONEKSI JARINGAN (tidak perlu diubah) ---
      # (Semua 66 link Leaf-Spine dan Client ada di sini)
      - endpoints: ["router1:eth1", "router5:eth1"]
      - endpoints: ["router1:eth2", "router6:eth1"]
      # ... dan seterusnya ...
      - endpoints: ["router4:eth16", "router20:eth4"]
      - endpoints: ["pc1:eth1", "router5:eth5"]
      - endpoints: ["pc2:eth1", "router20:eth5"]