global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'containerlab-nodes'
    static_configs:
      - targets:
          - '172.100.100.2:9100'
          - '172.100.100.3:9100'
          - '172.100.100.4:9100'
          - '172.100.100.5:9100'
  - job_name: 'sflow-rt-app'
    metrics_path: /app/prometheus/metrics
    static_configs:
      - targets: ['172.100.100.8:8008']