global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'containerlab-nodes'
    static_configs:
      - targets:
          - '172.100.100.2:9100'
          - '172.100.100.3:9100'
          - '172.100.100.4:9100'
          - '172.100.100.5:9100'
  - job_name: 'sflow-rt-general-metrics'
    metrics_path: /app/prometheus/scripts/export.js/metrics
    static_configs:
      - targets: ['172.100.100.8:8008']

  - job_name: 'sflow-rt-countries-scripted'
    metrics_path: /app/prometheus/scripts/export.js/flows/ALL/txt
    static_configs:
      - targets: ['172.100.100.8:8008']
    params:
      metric: ['sflow_country_bps']
      key: ['null:[country:ipsource:both]:unknown','null:[country:ipdestination:both]:unknown']
      label: ['src_country','dst_country']
      value: ['bytes']
      scale: ['8']
      aggMode: ['sum']
      minValue: ['1000']
      maxFlows: ['100']

  - job_name: 'sflow-rt-asns-scripted'
    metrics_path: /app/prometheus/scripts/export.js/flows/ALL/txt
    static_configs:
      - targets: ['172.100.100.8:8008']
    params:
      metric: ['sflow_asn_bps']
      key: ['null:[asn:ipsource:both]:unknown','null:[asn:ipdestination:both]:unknown']
      label: ['src_asn','dst_asn']
      value: ['bytes']
      scale: ['8']
      aggMode: ['sum']
      minValue: ['1000']
      maxFlows: ['100']