global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'containerlab-nodes'
    static_configs:
      - targets:
          - '172.100.100.2:9100'
          - '172.100.100.3:9100'
          - '172.100.100.4:9100'
          - '172.100.100.5:9100'
  - job_name: 'sflow-rt-analyzer'
    metrics_path: /prometheus/analyzer/txt
    static_configs:
      - targets: ['172.100.100.8:8008']
  - job_name: 'sflow-rt-metrics'
    metrics_path: /prometheus/metrics/ALL/ALL/txt
    static_configs:
      - targets: ['172.100.100.8:8008']
    metric_relabel_configs:
      - source_labels: ['agent', 'datasource']
        separator: ':'
        target_label: instance
  - job_name: 'sflow-rt-countries'
    metrics_path: /app/prometheus/scripts/export.js/flows/ALL/txt
    static_configs:
      - targets: ['172.100.100.8:8008']
    params:
      metric: ['sflow_country_bps']
      key: ['null:[country:ipsource:both]:unknown','null:[country:ipdestination:both]:unknown']
      label: ['src','dst']
      value: ['bytes']
      scale: ['8']
      aggMode: ['sum']
      minValue: ['1000']
      maxFlows: ['100']
  - job_name: 'sflow-rt-asns'
    metrics_path: /app/prometheus/scripts/export.js/flows/ALL/txt
    static_configs:
      - targets: ['172.100.100.8:8008']
    params:
      metric: ['sflow_asn_bps']
      key: ['null:[asn:ipsource:both]:unknown','null:[asn:ipdestination:both]:unknown']
      label: ['src','dst']
      value: ['bytes']
      scale: ['8']
      aggMode: ['sum']
      minValue: ['1000']
      maxFlows: ['100']